[project]
name = "project_name"
version = "0.0.1"
dependencies = [
  "numpy",
]

[project.scripts]
project_name = "project_name:main"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
